config/routes.rb
Datingscene::Application.routes.draw do
  namespace :admin do
    root 'questions#new'
    resources :questions
  end
  
  root 'site#index'
  get '/privacy-policy' => 'site#privacy', as: :privacy
  get '/terms-of-service' => 'site#terms', as: :terms
  get '/s/:key' => 'profiles#show', as: :scene
  
  resources :profiles, only: [:create]
  
  post '/load-file' => 'videos#update', as: :load_file
  
  # Error Pages
  get '/404', :to => 'errors#not_found'
  get '/422', :to => 'errors#unprocessable_entity'
  get '/500', :to => 'errors#internal_server_error'
end

app/models/interest.rb
class Interest < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  include VideoCompiler
  
  has_many :interests
  mount_uploader :video, ProfileVideoUploader
  
  after_initialize :generate_url_key
  before_create :download_temp_video
  
  def self.completed
    where(completed: true)
  end
    
  # The macro process to generating the new video
  # clean up old videos, and remove tmp videos from system
  # ensure new video is pushed to S3, and saved onto the model
  def compile_video
    @profile = self
    
    # Gather Question Videos
    collect_question_videos(@profile.question_ids.split(','))
    
    # Divide Source Video into 4 Sections
    split_source(@profile.tmp_video_path)
    
    # Combine and Order Question Videos with Source Clips
    combine_and_order_files(@clips)
    
    # Convert all pieces to match TS media type and create compile Recipe
    convert_all_media_to_ts(@order)
    create_recipe_final_ts
    
    # Compile 
    compile_recipe
    
    # Add Background Music
    seperate_audio_from_compiled_video
    mixin_background_was_with_audio_file
    overlay_mixed_audio_back_on_video
    
    # Create a Screenshot
    # TODO: push screetshot to aws::s3 and associate to profile
    # take_screenshot 
    
    # mark profile as completed with the new video url
    movie = FFMPEG::Movie.new('/tmp/videos/completed.mp4')
    self.video = movie
    self.completed = true
    save!
  end
  
  private
  
  def generate_url_key
    self.url_key = Time.now.to_i.to_s([31, 32, 33, 34].sample)
  end
  
  def download_temp_video
    self.tmp_video_path = download_tmp_video(original_url)
  end
  
end

app/models/question.rb
class Question < ActiveRecord::Base
  mount_uploader :video, QuestionVideoUploader
  
  def self.random_by_category
    group('id, category').order("RANDOM()").limit(4)
  end
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < AdminController
  
  def index
    @questions = Question.all
  end
  
  def new
    @question = Question.new
  end
  
  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to new_admin_question_path, notice: "Question has been saved."
    else
      flash[:error] = "Unable to save question"
      render :new
    end
  end
  
  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to admin_questions_path, notice: 'done'
  end
  
  protected
  
  def question_params
    params.require(:question).permit(:text, :category, :video)
  end
  
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'
  before_filter :authenticate_login
  
  USERNAME = ENV['ADMIN_LOGIN']
  PASSWORD = ENV['ADMIN_PASSWORD']
    
  protected
  
  def authenticate_login
    authenticate_or_request_with_http_basic do |username, password|
      username == USERNAME && password == PASSWORD
    end
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  layout 'errors'
  
  def not_found
    render status: 404
  end
  
  def internal_server_error
    render status: 500
  end
  
  def unprocessable_entity
    render status: 422
  end
  
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  def create
    @profile = Profile.new(profile_params)
    @profile.save!
    VideoCompilationWorker.perform_async(@profile.id)
    redirect_to root_path, notice: 'Your video will be available soon'
  end
  
  def show
    @profile = Profile.find(params[:key])
  end
  
  protected
  
  def profile_params
    params[:profile].merge!(question_ids: params[:question_ids].join(','))
    params.require(:profile).permit(:email, :url_key, :question_ids, :original_url)
  end
  
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  
  # too tired to care that I'm doing everything here
  def index
    @questions = Question.random_by_category
    @profile = Profile.new
    @profiles = Profile.completed
  end
  
  def privacy
  end
  
  def terms
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def javascript_cdn_tag(file, version, minify = true)
    cdn = '//cdnjs.cloudflare.com/ajax/libs'
    javascript_include_tag [cdn, file, version, [file, (minify ? 'min' : nil), 'js'].compact.join('.')].join('/')
  end
  
  def flash_message
    [:notice, :error, :alert, :warning, :info, :success].each do |key|
      return content_tag(:div, flash[key], class: "flash #{key}") if flash[key]
    end unless flash.empty?
  end
  
end

app/views/admin/questions/index.html.slim
.pull-right
  = link_to('+ Add question', new_admin_question_path)
h2 questions

table
  tr
    th Text
    th Category
    th Video
    th
  - @questions.each do |q|
    tr
      td= q.text
      td= q.category
      td= q.video.url
      td= link_to('delete', admin_question_path(q), method: :delete, confirm: 'delete')

app/views/admin/questions/new.html.slim
h2 New Question  
.form-box
  = form_for([:admin, @question], html: {multipart: true}) do |f|
    p
      = f.label(:text)
      = f.text_field :text 
    p
      = f.label(:category)
      = f.text_field :category 
    p
      = f.label(:video)
      = f.file_field :video
      
    p= f.submit('Upload')
    p= link_to('cancel', admin_questions_path)

app/views/layouts/admin.html.slim
doctype html
/[if lt IE 9]
  html class="iesux" lang="en"
/[if (gte IE 9)|!(IE)]
  html class="notie" lang="en"
head
  meta charset="utf-8"
  meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
  meta name="viewport" content="width=device-width, initial-scale=1.0"
  meta name="robots" content="noindex,nofollow"    
  meta name="resource-type" content="document"
  meta name="copyright" content="Copyright (c) LVRUG Team 4"
  = csrf_meta_tags
  title The Dating Scene | Admins Panel

  link rel="dns-prefetch" href="//ajax.googleapis.com"
  link rel="icon" type="image/png" href="/assets/favicon.ico"

  = stylesheet_link_tag 'admin', media: 'all' 
  /[if lt IE 9]
    = javascript_cdn_tag 'html5shiv', '3.6.1' 
  
body  
  .nav
    .nav-bar
      h1.title Admins Panel
  
  .container
    = yield 
  = jquery_include_tag :google 
  = javascript_include_tag 'application'

app/views/layouts/application.html.slim
doctype html
/[if lt IE 9]
  html class="iesux" lang="en"
/[if (gte IE 9)|!(IE)]
  html class="notie" lang="en"
head
  meta charset="utf-8"
  meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
  meta name="viewport" content="width=device-width, initial-scale=1.0"
  meta name="keywords" content=""
  meta name="description" content=""
  meta name="distribution" content="all"
  meta name="robots" content="all"    
  meta name="resource-type" content="document"
  meta name="copyright" content="Copyright (c) LVRUG Team 4"
  = csrf_meta_tags
  title The Dating Scene | A dating social experiment

  link rel="dns-prefetch" href="//ajax.googleapis.com"
  link rel="icon" type="image/png" href="/assets/favicon.png"

  = stylesheet_link_tag 'application', media: 'all' 
  /[if lt IE 9]
    = javascript_cdn_tag 'html5shiv', '3.6.1' 
  
body class="public"
  = yield(:hidden_nav)
  #main.content
    = flash_message
    = yield 
  = yield(:page_bottom) 
  = jquery_include_tag :google 
  = javascript_cdn_tag 'swfobject', '2.2' 
  = javascript_include_tag "application" 
  script var rumbleBannerPlacement = "bottom";
  = javascript_include_tag "http://s0.railsrumble.com/banner.js"
  
  

app/views/layouts/errors.html.slim
doctype html
html
  head
    title= yield(:page_title)
    = stylesheet_link_tag 'errors', media: 'screen'
 
  body class="error-page #{yield(:body_class)}"
    header.basic-head
      .container.text-center
        .info.pull-right
          p.small
            = link_to('Privacy Policy', privacy_path)
            = link_to('Terms of Service', terms_path)
        = link_to('Back Home', root_path, class: 'simple-btn')
        .logo.pull-left
          = link_to(image_tag('mini-logo.png'), root_path)
    .container
      section.content
        = yield(:error_box)

app/views/layouts/naked.html.slim
doctype html
/[if lt IE 9]
  html class="iesux" lang="en"
/[if (gte IE 9)|!(IE)]
  html class="notie" lang="en"
head
  title The Dating Scene | A dating social experiment

  link rel="dns-prefetch" href="//ajax.googleapis.com"

  = stylesheet_link_tag 'application', media: 'all' 
  /[if lt IE 9]
    = javascript_cdn_tag 'html5shiv', '3.6.1' 
  
body class="public"
  #webcam
  
  = link_to('click', '#', class: 'cam')
  = jquery_include_tag :google 
  = javascript_cdn_tag 'swfobject', '2.2' 
  = javascript_include_tag "application" 
  style
    | #webcam { width: 960px; height: 640px; position: absolute; top: 0; }
  script $(function(){$('a.cam').click(function(){$("#webcam").scriptcam();});});
  
  

app/views/layouts/panel.html.slim
doctype html
/[if lt IE 9]
  html class="iesux" lang="en"
/[if (gte IE 9)|!(IE)]
  html class="notie" lang="en"
head
  meta charset="utf-8"
  meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
  meta name="viewport" content="width=device-width, initial-scale=1.0"
  meta name="keywords" content=""
  meta name="description" content=""
  meta name="distribution" content="all"
  meta name="robots" content="all"    
  meta name="resource-type" content="document"
  meta name="copyright" content="Copyright (c) LVRUG Team 4"
  = csrf_meta_tags
  title The Dating Scene | Admins Panel

  link rel="dns-prefetch" href="//ajax.googleapis.com"
  link rel="icon" type="image/png" href="/assets/favicon.ico"

  = stylesheet_link_tag 'admins_panel', media: 'all'
  = yield :stylesheets 
  /[if lt IE 9]
    = javascript_cdn_tag 'html5shiv', '3.6.1' 
  = javascript_cdn_tag 'modernizr', '2.6.2' 
  
body  
  #main.content
    = yield

app/views/profiles/show.html.slim
section
  header.site-head
    .container
      .info
        = link_to('Make a Video', '#', class: 'simple-btn action scroll', 'data-page' => '3')
        p.small
          = link_to('Privacy Policy', privacy_path)
          = link_to('Terms of Service', terms_path)
      = link_to(image_tag('logo.png', alt: 'The Dating Scene'), root_path)
  .container
    .flowplayer
      video controls="controls" autobuffer="autobuffer" width="640" height="480"
        source src="#{@profile.video.url}" type="video/mp4"

app/views/scenes/_index.html.slim
section.page2
  .container
    h2 Scenes
    - @profiles.each_slice(4) do |group|
      .video-row
        - group.each do |profile|
          .box
            = link_to('#', class: 'img', 'data-reveal-id' => "sceneModal-#{profile.id}") do
              = image_tag('default-thumb.png')
              .hover &nbsp;
            div id="sceneModal-#{profile.id}" class="reveal-modal large"
              a href="#" class="close-reveal-modal"
                = image_tag('close.png')
              .flowplayer
                video controls="controls" autobuffer="autobuffer" width="640" height="480"
                  source src="#{profile.video.url}" type="video/mp4"

              .overlay-interest
                h3 So, what did you think?
                = link_to("I'm Interested", "##{profile.id}", class: 'action link-block')
                = link_to('View More Videos', "##{profile.id}", 'data-close' => "sceneModal-#{profile.id}", class: 'cancel link-block')
              .overlay-request
                h3 Fill out the info below and we'll put you in touch
                = form_tag('') do
                  .left-col
                    .text-field
                      = email_field_tag(:email, '', placeholder: 'you@example.com', required: true)
                  .right-col
                    p
                      | Your Gender:
                      = link_to(image_tag('female.png'), '#', class: 'set-female')
                      = hidden_field_tag(:gender, '', id: 'set-female')
                      = link_to(image_tag('male.png'), '#', class: 'set-male')
                      = hidden_field_tag(:gender, '', id: 'set-male')
                    .btn-group
                      = link_to('Cancel', "##{profile.id}", 'data-close' => "sceneModal-#{profile.id}", class: 'link-small cancel')
                      = submit_tag('Send', class: 'link-small action')
                  br clear="both"

app/views/scenes/_new.html.slim
section.page3
  .container
    h2 Your Scene
    .webcam-box.text-center
      = form_for(@profile) do |f|
        = f.hidden_field(:original_url)
        .preload
          h3 Before you can start, you'll need to allow us to access your webcam.
          = link_to('Ok I Understand', '#', class: 'ready-cam action')
        .overlay-start.hidden
          p Alright, so here's how easy it is to get on The DatingScene. We will ask you 4 questions, and you'll have 5 seconds to answer each one. It's that simple. 
          = link_to("Let's Do This!", '#', class: 'start-video action', 'data-reveal-id' => 'webcamModal')
        - @questions.each_with_index do |question, index|
          .overlay-question.hidden data-question="#{index + 1}"
            = hidden_field_tag('question_ids[]', question.id)
            h3.question-title Question #{index + 1}
            p.text= question.text
            = link_to("I'm ready", '#', class: 'answer action')
        .overlay-complete.hidden
          h3 Thanks for making a scene!
          p Your video will be available to view in the next few minutes from the link below.
          = f.hidden_field(:url_key)
          h3= link_to(scene_url(@profile.url_key), scene_url(@profile.url_key), target: '_blank')
          p Enter your email, and we'll contact you if someone is interested in getting to know you better.
          .text-field
            = f.email_field(:email, placeholder: 'you@example.com', required: true)
            = f.submit('Send', class: 'btn')
          small.angry note* email is required to generate your video. 
      
- content_for(:page_bottom) do
  #webcamModal.reveal-modal.large
    #webcam
    .progress
      .bar

app/views/site/index.html.slim
- content_for(:hidden_nav) do
  nav.hidden-nav
    .container.text-center
      .info.pull-right
        p.small
          = link_to('Privacy Policy', privacy_path)
          = link_to('Terms of Service', terms_path)
      .logo.pull-left
        = link_to(image_tag('mini-logo.png', alt: 'The Dating Scene'), root_path)
  
section
  header.site-head
    .container
      .info
        = link_to('Make a Video', '#', class: 'simple-btn action scroll', 'data-page' => '3')
        p.small
          = link_to('Privacy Policy', privacy_path)
          = link_to('Terms of Service', terms_path)
      = link_to(image_tag('logo.png', alt: 'The Dating Scene'), root_path)
  .page1
    .container
      h1.text-center.page-title
        p The Dating Scene does some cool stuff that is different than other dating sites.
        p It records realtime video of the user's response to a series of questions.
      h2 How It Works
      ul.steps
        li
          .circle 1
          p We will ask you for access to use your webcam. Give us access by clicking the "allow" button. Make sure your hair is done!
        li
          .circle 2
          p You will answer up to 4 questions so we get to know you a bit better. We can then record these answers to make your video.
        li
          .circle 3
          p With all the answers you've given us, we take those, and create a unique video for you to share, and get people to know the real you.
      .btn-row
        = link_to('Make a Video', '#', class: 'action scroll', 'data-page' => '3')
        = link_to('View Others', '#', class: 'action scroll', 'data-page' => '2')

= render('scenes/index')
= render('scenes/new')  

app/views/site/privacy.html.slim
nav.page-header
  .container.text-center
    .info.pull-right
      p.small
        = link_to('Privacy Policy', privacy_path)
        = link_to('Terms of Service', terms_path)
    .logo.pull-left
      = link_to(image_tag('mini-logo.png', alt: 'The Dating Scene'), root_path)
.static-page
  .container
    h1.page-title Privacy Policy
    strong we won't sell your email, or spam you, or stalk you, or other weird stuff.

app/views/site/terms.html.slim
nav.page-header
  .container.text-center
    .info.pull-right
      p.small
        = link_to('Privacy Policy', privacy_path)
        = link_to('Terms of Service', terms_path)
    .logo.pull-left
      = link_to(image_tag('mini-logo.png', alt: 'The Dating Scene'), root_path)
.static-page
  .container
    h1.page-title Terms of Service
    strong you gotta be over 17 to be on here. Other legal things....